# Java Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Gradle Properties
publishing_version=0.1.+

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.119
neo_version_range=[21.1.119,)
loader_version_range=[1,)

# Neo Properties
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Mod Properties
mod_group_id=com.calemi.ccore
mod_id=ccore
mod_name=CCore
mod_version=1.0.0
mod_description=Contains useful functions that my mods can use.
mod_authors=Calemi
mod_license=All Rights Reserved

mod_release_type=release
curseforge_project_id=573646
modrinth_project_id=hfRaP0LY

# Other Mod Properties
jei_file_id=5846880